export const ADD_DRUGS = 'ADD DRUGS'
export const FETCH_DRUGS = 'FETCH DRUGS'
export const FETCH_DRUG = 'FETCH DRUG'
export const DELETE_DRUGS = 'DELETE DRUGS'
export const UPDATE_DRUGS = 'UPDATE DRUGS'
export const FETCH_PRICES = 'FETCH PRICES'
